#
# 玩家当前的等级阶级
#
等阶:
  初级:
    达成等级: 0
    达成消耗: []
    #升级增加技能点
    技能点: 3

# 玩家最大的等级
# 每级的技能点根据等阶
最大等级: 100

等级算法: "({level} * ({level} + 200) ) + {pf} * 100"

属性配置:
  HEALTH:
    最大技能点: 100
    # 在基础上增加
    属性增加: "{当前属性} * ({技能点} * 0.1)"
  DAMAGE:
    最大技能点: 100
    # 在基础上增加
    属性增加: "{当前属性} * ({技能点} * 0.1)"
  DEFENSE:
    最大技能点: 100
    # 在基础上增加
    属性增加: "{当前属性} * ({技能点} * 0.1)"
  MISS:
    最大技能点: 100
    # 在基础上增加
    属性增加: "{当前属性} * ({技能点} * 0.1)"
  MUST_DAMAGE:
    最大技能点: 100
    # 在基础上增加
    属性增加: "{当前属性} * ({技能点} * 0.1)"
  RESISTANCE:
    最大技能点: 100
    # 在基础上增加
    属性增加: "{当前属性} * ({技能点} * 0.1)"
  PENETRATION:
    最大技能点: 100
    # 在基础上增加
    属性增加: "{当前属性} * ({技能点} * 0.1)"

# 取整为 四舍五入
技能点消耗递增算法: "1 + ({技能点} * 0.3)"

