name: LevelAwakenSystem
main: com.smallaswater.levelawakensystem.LevelAwakenSystem
version: "1.0.0"
api: ["1.0.0","1.0.8"]
author: "若水"
load: POSTWORLD
loadbefore:
  - AutoUpData
softdepend:
  - Tips
