#    _                   _    _                _
# | |    _____   _____| |  / \__      ____ _| | _____ _ __
# | |   / _ \ \ / / _ \ | / _ \ \ /\ / / _` | |/ / _ \ '_ \
# | |__|  __/\ V /  __/ |/ ___ \ V  V / (_| |   <  __/ | | |
# |_____\___| \_/ \___|_/_/   \_\_/\_/ \__,_|_|\_\___|_| |_|
#此处设定是属性在范围里变换的随机值

#极低: 1 低  2 较低: 3 中等 4 较高: 5 高 6 极高 7
设定:
 §r武者: [0,0]
 §7一品越凡: [0,2]
 §f二品真师: [1,3]
 §a三品战王: [1,4]
 §d四品武皇: [2,5]
 §6五品灵皇: [2,6]
 §6六品真君: [3,7]
 §e七品尊者: [3,8]
 §l§c八品玄圣: [4,9]
 §l§o§d九品劫仙: [4,10]

等级最大值: 100
#等级算法（写死 ） (等级 * (等级 + 200) ) + 设定 * 100
#后面的数值是设定 是设定!
#初始属性: 根据天赋

#升级加成: 根据玩家设定 去选设置值
# &item 奖励物品 &money奖励金钱 &cmd 奖励指令 后面的 &是别名
升级奖励:
 3: ["100&money&金币","264:0:2&item&钻石"]

#天赋 * 消耗
#允许进阶等级(写死) 天赋 * 10
进阶消耗: 10000
#此物品请参考文件夹/RPG/Items
#收集物品进阶评级
#所有需求均为[升级奖励除外] 物品id:特殊值:数量&item 或 消耗品名称:数量&remove
物品收集:
 1: []
 2: []
 3: []
 4: []
 5: []
 6: []
 7: []
 8: []
 9: []
矿物经验:
 16: 2
 15: 3
 14: 4
 21: 5
 56: 6
击杀经验: 6

是否开启头部显示: true

头部显示: "§e[{属性}] §b· {name} §f-§r[{天赋}]§r{换行}Lv .{level} [{h}/{mh}]"

是否开启底部显示: true

底部显示类型: "tip"

底部显示: "§d<§r{属性}§d>§bLv.{level}  §eExp. {exp} / {mexp}  §c♥ {h}/{mh}  §f~[§r{天赋}§f]~ "

是否更改聊天内容: true

聊天显示: "§a[{天赋}§r§a]§6Lv.§a {level}§d>>§b{name}§r §e>>§r"

是否开启Boss血条显示: true

Boss血条显示内容: "§e§l血量  {h} / {mh} "

#此消耗是基础消耗 根据觉醒次数的增加而增加 算法: 次数*消耗
觉醒消耗: 1000


